# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('competencies', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=200)),
                ('project_description', tinymce.models.HTMLField()),
                ('small_image', models.FileField(upload_to=b'')),
                ('large_image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
